#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression --message="Updating Ferdium Server URL..." --weight=2
ynh_change_url_nginx_config

# Re-render the environment because APP_URL and MAIL_SENDER depend on the domain.
app_key="$(ynh_app_setting_get --app="$app" --key=app_key)"
ynh_config_add --template=".env" --destination="$install_dir/.env"
chmod 600 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"

ynh_systemd_action --service_name="$app" --action=restart --log_path="systemd"
