#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression --message="Installing Ferdium Server sources..." --weight=5
install_ferdium_sources

ynh_script_progression --message="Installing Node.js dependencies and building Ferdium Server..." --weight=20
install_ferdium_dependencies

ynh_script_progression --message="Configuring Ferdium Server..." --weight=2
app_key="$(ynh_string_random --length=64)"
ynh_app_setting_set --app="$app" --key=app_key --value="$app_key"

ynh_config_add --template=".env" --destination="$install_dir/.env"
chmod 600 "$install_dir/.env"
chown -R "$app:$app" "$install_dir" "$data_dir"

ynh_script_progression --message="Running database migrations..." --weight=5
run_ferdium_migrations

ynh_script_progression --message="Configuring systemd service..." --weight=2
ynh_config_add_systemd
systemctl enable --now "$app.service"

ynh_script_progression --message="Configuring NGINX..." --weight=2
ynh_config_add_nginx
ynh_systemd_action --service_name=nginx --action=reload
