#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression --message="Restoring Ferdium Server files..." --weight=5
ynh_restore_file --origin_path="$install_dir"
ynh_restore_file --origin_path="$data_dir"
ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_restore_file --origin_path="/etc/systemd/system/$app.service"

chown -R "$app:$app" "$install_dir" "$data_dir"
systemctl daemon-reload
systemctl enable "$app.service"
ynh_systemd_action --service_name="$app" --action=restart --log_path="systemd"
ynh_systemd_action --service_name=nginx --action=reload
