#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression --message="Stopping Ferdium Server..." --weight=1
ynh_systemd_action --service_name="$app" --action=stop

ynh_script_progression --message="Updating Ferdium Server sources..." --weight=5
install_ferdium_sources

ynh_script_progression --message="Installing dependencies and rebuilding..." --weight=20
install_ferdium_dependencies

app_key="$(ynh_app_setting_get --app="$app" --key=app_key)"
ynh_config_add --template=".env" --destination="$install_dir/.env"
chmod 600 "$install_dir/.env"
chown -R "$app:$app" "$install_dir" "$data_dir"

ynh_script_progression --message="Running database migrations..." --weight=5
run_ferdium_migrations

ynh_config_add_systemd
ynh_config_add_nginx

ynh_script_progression --message="Starting Ferdium Server..." --weight=2
ynh_systemd_action --service_name="$app" --action=restart --log_path="systemd"
ynh_systemd_action --service_name=nginx --action=reload
